name: Library build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  lib-build:
    runs-on: ubuntu-20.04
    concurrency: ci-${{ github.ref }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup and cache dependencies
      uses: cybercryptio/build-setup-action@master

    - name: Lint
      run: make lint

    - name: Build
      run: make build

    - name: Run tests
      run: make tests

    - name: Install GitVersion
      if: github.ref_name == 'master'
      uses: gittools/actions/gitversion/setup@v0.9.13
      with:
        versionSpec: '5.x'

    - name: Determine Version
      if: github.ref_name == 'master'
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.13
      with:
        additionalArguments: '/overrideconfig mode=ContinuousDeployment'

    - name: Create tag
      if: github.ref_name == 'master'
      run: |
        git tag v${{ steps.gitversion.outputs.semVer }}
        git push origin v${{ steps.gitversion.outputs.semVer }}

