name: Library build

on: push

jobs:
  lib-build:
    runs-on: ubuntu-20.04
    concurrency: ci-${{ github.ref }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Setup and cache dependencies
      uses: cyber-crypt-com/build-setup-action@master

    - name: Lint
      run: make lint

    - name: Build
      run: make build

    - name: Run tests
      run: make tests

    - name: Install GitVersion
      if: github.ref_name == 'master'
      uses: gittools/actions/gitversion/setup@v0.9.13
      with:
        versionSpec: '5.x'

    - name: Determine Version
      if: github.ref_name == 'master'
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.13
      with:
        additionalArguments: '/overrideconfig mode=Mainline'

    - name: Create tag
      if: github.ref_name == 'master'
      run: |
        git tag ${{ steps.gitversion.outputs.semVer }}
        git push origin ${{ steps.gitversion.outputs.semVer }}

