name: Snyk scan

on: push

jobs:
  scan-go:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install Snyk CLI
      uses: snyk/actions/setup@master

    - name: Scan go projects
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: snyk test --all-projects
